(setq lexical-binding t)
(setq max-specpdl-size 10000)
(setq max-lisp-eval-depth 10000)
(define-obsolete-function-alias 'string-to-int 'string-to-number "22.1")
(add-to-list 'load-path "./site-lisp/bigint/")
(add-to-list 'load-path "./site-lisp/s")
(require 's)
(require 'bigint)
(defun T () t)
(defun F () nil)
(defalias 'take's-left)
(defalias 'drop's-right)
(funcall (funcall (lambda (var0)
                    (funcall (lambda (var1)
                               (funcall var0
                                        (funcall var1 var1)))
                             (lambda (var1)
                               (funcall var0
                                        (funcall var1 var1)))))
                  (lambda (var0)
                    (lambda (var1)
                      (if (= var1 0)
                          "........................................................................................................................................................................................................"
                        (s-concat (funcall var0 (/ var1 4 ))
                                  (take 1 (drop (% var1 4) ".\n#L")))))))
         1)
