[package]
name = "solver"
version = "0.1.0"
edition = "2018" 

[dependencies]
serde_json = { version = "1.0.85" }
chrono = { version = "0.4.26" }
serde = { version = "1.0", features = ["derive"] }
rand = { version = "0.8.5" }