name: Node

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [instance2024-1-1]
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: pwd
        run: pwd
