name: PullRepo

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Pull /var/www/repo
        run: cd /var/www/repo && git pull
